### ISSUE TITLE
Problem with test-match scores 

### ISSUE THREAD

**Issue by Zapx86** [psibi/cricbuzz#1]
The details of ODI are perfect but there seems to be missing details of test-match scores. There is absolutely no information about test-matches except for the state of the match.

**Comment by psibi** [comment]
The code is very small. Probably there is some parsing which I have missed out. Want to send a PR fixing this ?

**Comment by Zapx86** [comment]
Yeah.. I am fixing it. Getting the details right.

**Comment by psibi** [comment]
Closing the issue, since it is fixed by your patch.

**Comment by Zapx86** [comment]
Yeah okay.
